name: Tests
on: [push]

jobs:
  build-temp-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: build-temp-container
        run: |
          docker build -t app-token:temp -f prebuild.Dockerfile .
          mkdir -p artifacts
          docker save app-token:temp > artifacts/docker-image.tar
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: artifacts

  test-container:
    needs: [build-temp-container]
    runs-on: ubuntu-latest
    steps:
    - name: Download Docker Image (Artifact)
      uses: actions/download-artifact@v2
      with:
        name: docker-artifact
        path: artifacts
    - name: Run test in Docker
      run: |
        cd artifacts
        docker load < docker-image.tar
  
    - uses: actions/checkout@master
      
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v1
    #   env:
    #     INPUT_APP_PEM: ${{ secrets.APP_PEM }}
    #     INPUT_APP_ID: ${{ secrets.APP_ID }}

    # tested with https://github.com/apps/fastpages-chatops
    - name: test
      id: test
      uses: docker://app-token:temp
      env:
        INPUT_APP_PEM: ${{ secrets.APP_PEM }}
        INPUT_APP_ID: ${{ secrets.APP_ID }}


       # tested withhttps://github.com/apps/fastpages-chatops
    - name: final-test
      uses: machine-learning-apps/actions-app-token@master
      with:
        APP_PEM: ${{ secrets.APP_PEM }}
        APP_ID: ${{ secrets.APP_ID }}